DO $$
BEGIN
  EXECUTE format('GRANT USAGE ON SCHEMA util TO %I', current_user);
  EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA util TO %I', current_user);
  EXECUTE format('ALTER DEFAULT PRIVILEGES IN SCHEMA util GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO %I', current_user);

  EXECUTE format('GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA util TO %I', current_user);
  EXECUTE format('GRANT EXECUTE ON ALL PROCEDURES IN SCHEMA util TO %I', current_user);
  EXECUTE format('ALTER DEFAULT PRIVILEGES IN SCHEMA util GRANT EXECUTE ON FUNCTIONS TO %I', current_user);
  EXECUTE format('ALTER DEFAULT PRIVILEGES IN SCHEMA util GRANT EXECUTE ON PROCEDURES TO %I', current_user);
EXCEPTION WHEN OTHERS THEN
  RAISE NOTICE 'util grants skipped: %', SQLERRM;
END$$;
